# Secret of Github Webhook to verify the request is from Github
webhook_secret = "secret"

# Github token and repo to regulate
gh_token = "token"
gh_repo = "owner/repo"



[OpenAI]
org = "your-org-id"
key = "your-api-key"
model = "omni-moderation-latest"
threshold = 0.7
